Repository DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous, pull requests merged in 2024-11, with the labels that each got.

#25 [Feat] 룸플랜 기능구현
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/Data/Foundation/RoomPlanManager.swift
  ZipZipSa/ZipZipSa/Data/Model/SampleRoom.swift
  ZipZipSa/ZipZipSa/Presentation/Custom/CustomLineDivider.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/mainPic_sample.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/mainPic_sample.imageset/IMG_9658.jpeg
  ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
  ZipZipSa/ZipZipSa/Resource/Extension/UIImage+.swift
  ZipZipSa/ZipZipSa/Resource/Extension/UIView+.swift
  ZipZipSa/ZipZipSa/Resource/Extension/View+.swift
Labels: Reviewing, Feather

#28 [Setting] #23 - 체크리스트 기능 구현
  ZipZipSa/ZipZipSa/Data/Model/Checklist/ChecklistCategory.swift
  ZipZipSa/ZipZipSa/Data/Model/Checklist/ChecklistHazard.swift
  ZipZipSa/ZipZipSa/Data/Model/Checklist/ChecklistItem.swift
  ZipZipSa/ZipZipSa/Data/Model/Checklist/ChecklistQuestion.swift
  ZipZipSa/ZipZipSa/Data/Model/Checklist/ChecklistSpaceType.swift
  ZipZipSa/ZipZipSa/Data/Model/Checklist/ChecklistType.swift
  ZipZipSa/ZipZipSa/Presentation/Checklist/ChecklistRowAnswerSectionView.swift
  ZipZipSa/ZipZipSa/Presentation/Checklist/ChecklistRowView.swift
  ZipZipSa/ZipZipSa/Presentation/Checklist/ChecklistTabView.swift
  ZipZipSa/ZipZipSa/Presentation/Checklist/ChecklistView.swift
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/AppIcon.appiconset/App Icon_@3x.png
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/crossTip.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/crossTip.imageset/Frame 242.png
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/crossTip.imageset/Frame 242@2x.png
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/crossTip.imageset/Frame 242@3x.png
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/remark.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/remark.imageset/Group 37.png
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/remark.imageset/Group 37@2x.png
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Dummy/remark.imageset/Group 37@3x.png
Labels: Reviewing, Nagi

#27 [Feat] #26 - 주변시설 불러오기 기능
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
  ZipZipSa/ZipZipSa/Data/Foundation/FacilityChecker.swift
  ZipZipSa/ZipZipSa/Data/Model/PlaceRespnse.swift
  ZipZipSa/ZipZipSa/Info.plist
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/24.circle.fill.imageset/24.circle.fill.svg
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/24.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/cart.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/cart.circle.fill.imageset/cart.circle.fill.svg
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/cross.case.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/cross.case.circle.fill.imageset/cross.case.circle.fill.svg
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/daiso.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/daiso.circle.fill.imageset/Daiso.svg
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/pill.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/pill.circle.fill.imageset/pill.circle.fill.svg
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/tree.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/tree.circle.fill.imageset/tree.circle.fill.svg
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/washer.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Icon/washer.circle.fill.imageset/washer.circle.fill.svg
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/mainPic_sample.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Assets.xcassets/Image/mainPic_sample.imageset/IMG_9658.jpeg
  ZipZipSa/ZipZipSa/Resource/Constant/Facility.swift
  ZipZipSa/ZipZipSa/Resource/Constant/NetworkError.swift
  ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
  ZipZipSa/ZipZipSa/Resource/Manager/LocationManager.swift
  ZipZipSa/ZipZipSa/Resource/Manager/RoomPlanManager.swift
Labels: Reviewing, Feather

#39 [Feat] #38 - 주소검색 및 현재위치 가져오기 기능
  ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
  ZipZipSa/ZipZipSa/Data/Foundation/AddressSearchManager.swift
  ZipZipSa/ZipZipSa/Data/Model/APIResponse.swift
  ZipZipSa/ZipZipSa/Data/Model/SampleRoom.swift
  ZipZipSa/ZipZipSa/Data/Model/TestFavoriteAddress.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
  ZipZipSa/ZipZipSa/Presentation/Test/TestFavAddressEnterView.swift
  ZipZipSa/ZipZipSa/Presentation/Test/TestRoomAddressEnterView.swift
  ZipZipSa/ZipZipSa/Resource/Constant/Facility.swift
  ZipZipSa/ZipZipSa/Resource/Constant/NetworkError.swift
  ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
Labels: Reviewing, Feather

#41 [Design] #40 - RoomScanView UI 구현
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanAssistantView/DoneScanningView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanAssistantView/ScanningView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanInfoView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/UnsupportedDeviceView.swift
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Icon/daiso.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Icon/daiso.circle.fill.imageset/daiso.circle.fill.svg
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Icon/pill.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Icon/tree.circle.fill.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/Dummy/basicYongboogiHeadColor.imageset/charMain.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/Dummy/basicYongboogiHeadColor.imageset/charMain@2x.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/Dummy/basicYongboogiHeadColor.imageset/charMain@3x.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charRoomScanInfo.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charRoomScanInfo.imageset/charRoomScanInfo.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charRoomScanInfo.imageset/charRoomScanInfo@2x.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charRoomScanInfo.imageset/charRoomScanInfo@3x.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charUnsupportedDevice.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charUnsupportedDevice.imageset/charUnsupportedDevice.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charUnsupportedDevice.imageset/charUnsupportedDevice@2x.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/charUnsupportedDevice.imageset/charUnsupportedDevice@3x.png
  ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
  ZipZipSa/ZipZipSa/Resource/Manager/RoomPlanManager.swift
Labels: Reviewing, Feather

#44 [Fix] #43 - 결과카드 공유할 때 카드가 잘리는 문제 해결
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
  ZipZipSa/ZipZipSa/Resource/Constant/Color+.swift
  ZipZipSa/ZipZipSa/Resource/Extension/View+.swift
Labels: Reviewing, Feather

#46 [Design] #45 - ResultCardView UI작업(작업중)
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
Labels: Reviewing, Feather

#52 [ Design] #50 - ResultCardView UI구현
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
  ZipZipSa/ZipZipSa/Presentation/Custom/ScoreGraph.swift
  ZipZipSa/ZipZipSa/Presentation/Custom/ZZSSperator.swift
  ZipZipSa/ZipZipSa/Presentation/Custom/ZZSTag.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCard.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCardHeaderView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCardView.swift
Labels: In Progress, Feather

#57 Design/#51 - SettingView 구현
  ZipZipSa/ZipZipSa/Data/Model/Category.swift
  ZipZipSa/ZipZipSa/Presentation/Setting/CategoryChangeView.swift
  ZipZipSa/ZipZipSa/Presentation/Setting/PrivacyPolicyView.swift
  ZipZipSa/ZipZipSa/Presentation/Setting/SettingView.swift
  ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
Labels: Reviewing, Lemony

#58 [Design] #56 - ResultCardView 데이터 없을 경우 분기처리
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCardHeaderView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCardView.swift
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/ResultCard/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/ResultCard/charResultCard.imageset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/ResultCard/charResultCard.imageset/charResultCard.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/ResultCard/charResultCard.imageset/charResultCard@2x.png
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/Image/ResultCard/charResultCard.imageset/charResultCard@3x.png
Labels: Feather

#62 [Feat] #61 - EssentialInfoView에서 주변시설 불러오기 기능 구현
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/EssentialInfoView.swift
Labels: Reviewing, Feather

#65 [Feat] #64 - NavigationPathModel 구현
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/EssentialInfoView.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathModel/PathModel+.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathModel/PathModel.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathModel/PathModelProtocol.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathType/Screen.swift
Labels: Reviewing, Feather

#69 [Fix] #66 - FullScreenCover로 올라왔을 때 모델을 캡쳐할 수 있도록 수정
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/EssentialInfoView.swift
  ZipZipSa/ZipZipSa/Presentation/HomeList/HomeListView.swift
  ZipZipSa/ZipZipSa/Presentation/Main/MainView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanAssistantView/DoneScanningView.swift
  ZipZipSa/ZipZipSa/Resource/Extension/UIWindow.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathModel/PathModel+.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathModel/PathModel.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathModel/PathModelProtocol.swift
  ZipZipSa/ZipZipSa/Resource/Manager/Path/PathType/Screen.swift
Labels: Reviewing, Feather

#71 [Fix] #70 - RoomScanView 등에서 모델 없이 결과시트로 넘어가도록 함
  ZipZipSa/ZipZipSa/Presentation/Checklist/ChecklistView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanAssistantView/DoneScanningView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanInfoView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/RoomScanView.swift
  ZipZipSa/ZipZipSa/Presentation/RoomScan/UnsupportedDeviceView.swift
Labels: SuperTopDeveloper, Feather

#75 [Fix] #73 - ResultCardView UI 수정 및 코드수정
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCardHeaderView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCardView.swift
Labels: Reviewing, Feather

#78 [Fix] #77 - ResutCardView 코드수정 및 세팅 수정
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/Presentation/Result/ResultCardView.swift
  ZipZipSa/ZipZipSa/Presentation/Result/ShareCardView.swift
  ZipZipSa/ZipZipSa/Resource/Constant/ZipLiteral.swift
Labels: SuperTopDeveloper, Feather

#80 [Chore] #79 - 설정뷰 하단에 앱 현재버전 명시
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/Presentation/Setting/SettingView.swift
Labels: Reviewing, Feather

#85 [Feat] #59 - 구글맵 -> 맵킷으로 이사
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/TestAddressEnterView.swift
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/TestEssentialInfoView.swift
  ZipZipSa/ZipZipSa/Resource/Constant/Facility.swift
  ZipZipSa/ZipZipSa/Resource/Extension/Array+.swift
  ZipZipSa/ZipZipSa/Resource/Manager/TestFacilityManager.swift
  ZipZipSa/ZipZipSa/Resource/Manager/TestLocationManager.swift
Labels: Reviewing, Feather

#87 [Feat] #86 - 구글맵 -> MapKit이사 작업 완료
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZipZipSa/ZipZipSa/App/ZipZipSaApp.swift
  ZipZipSa/ZipZipSa/Data/Foundation/AddressSearchManager.swift
  ZipZipSa/ZipZipSa/Data/Foundation/FacilityChecker.swift
  ZipZipSa/ZipZipSa/Data/Model/APIResponse.swift
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/AddressEnterView.swift
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/EssentialInfoView.swift
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/TestAddressEnterView.swift
  ZipZipSa/ZipZipSa/Presentation/EssentialInformation/TestEssentialInfoView.swift
  ZipZipSa/ZipZipSa/Presentation/Test/TestFavAddressEnterView.swift
  ZipZipSa/ZipZipSa/Presentation/Test/TestRoomAddressEnterView.swift
  ZipZipSa/ZipZipSa/Resource/GoogleMapService/APIResponse.swift
  ZipZipSa/ZipZipSa/Resource/GoogleMapService/AddressSearchManager.swift
  ZipZipSa/ZipZipSa/Resource/GoogleMapService/TestFavAddressEnterView.swift
  ZipZipSa/ZipZipSa/Resource/GoogleMapService/TestLocationManager.swift
  ZipZipSa/ZipZipSa/Resource/GoogleMapService/TestRoomAddressEnterView.swift
  ZipZipSa/ZipZipSa/Resource/Manager/FacilityManager.swift
  ZipZipSa/ZipZipSa/Resource/Manager/LocationManager.swift
  ZipZipSa/ZipZipSa/Resource/Manager/TestLocationManager.swift
Labels: SuperTopDeveloper, Feather
