Repository DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous, pull requests merged in 2024-10, with the labels that each got.

#2 [PR/#1] 이슈, PR테스트
  Eggong/Eggong/ContentView.swift
Labels: enhancement

#4 [Setting] #3 - 프로젝트파일 폴더링
  Eggong/Eggong.xcodeproj/project.pbxproj
  Eggong/Eggong/App/EggongApp.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/FirebaseFoundation.swift
  Eggong/Eggong/Data/Network/Service/PlaceService.swift
  Eggong/Eggong/Data/Network/Service/UserService.swift
  Eggong/Eggong/Data/Repository/File.swift
  Eggong/Eggong/Data/Repository/PlaceRepository.swift
  Eggong/Eggong/Data/Repository/UserRepository.swift
  Eggong/Eggong/Presentation/ContentView.swift
  Eggong/Eggong/Presentation/Home/HomeAssistantView/HomeCardView.swift
  Eggong/Eggong/Presentation/Home/HomeView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailStoryImageView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailView.swift
  Eggong/Eggong/Resource/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  Eggong/Eggong/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Eggong/Eggong/Resource/Assets/Assets.xcassets/Contents.json
  Eggong/Eggong/Resource/Constant/StringLiterals.swift
  Eggong/Eggong/Resource/Extension/Font+.swift
  Eggong/Eggong/Resource/Manager/HapticManager.swift
Labels: Reviewing, Nagi, Feather

#7 [Network] #5 - Firebase 통신을 위한 기초 모듈 구현
  Eggong/Eggong.xcodeproj/project.pbxproj
  Eggong/Eggong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Eggong/Eggong/App/EggongApp.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/Auth/FirebaseAuthFoundation.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/FirebaseFoundation.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/FirebaseModelProtocol.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/FirebaseResultCase/FirebaseError.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/FirebaseResultCase/FirebaseLogger.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/FirebaseResultCase/FirebaseSuccess.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/Firestore/FirebaseFirestoreFoundation.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/Firestore/FirestoreQueryOption.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/Firestore/FirestoreSortOption.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/Storage/FirebaseStorageFoundation.swift
  Eggong/Eggong/GoogleService-Info.plist
Labels: Reviewing, Nagi

#8 [Network] #5-2 기본 모델 통신 서비스 구현
  Eggong/Eggong/Data/Model/Place.swift
  Eggong/Eggong/Data/Model/PlaceDetail.swift
  Eggong/Eggong/Data/Model/User.swift
  Eggong/Eggong/Data/Network/FirebaseFoundation/Storage/FirebaseStorageFoundation.swift
  Eggong/Eggong/Data/Network/Service/PlaceDetailService.swift
  Eggong/Eggong/Data/Network/Service/PlaceService.swift
  Eggong/Eggong/Data/Network/Service/UserService.swift
  Eggong/Eggong/Resource/Constant/StringLiterals.swift
Labels: Reviewing, Nagi

#10 [Design] #6 - PlaceDetailView UI작업
  Eggong/Eggong.xcodeproj/project.pbxproj
  Eggong/Eggong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Eggong/Eggong/Data/Model/PlaceDetail.swift
  Eggong/Eggong/Presentation/Component/ActionButton.swift
  Eggong/Eggong/Presentation/Component/NavigationBackButton.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailDescriptionView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailFooterView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailHeaderView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailStoryImageView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailStoryView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailView.swift
Labels: Reviewing, Feather

#12 [Fix] #6-2 - 사용하지 않는 파일 삭제
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailDescriptionView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailFooterView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailHeaderView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailStoryImageView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailAssistantView/PlaceDetailStoryView.swift
Labels: Reviewing, Feather

#17 [Design] #16 - 폰트 및 컬러시스템 통일
  Eggong/Eggong/Presentation/Component/ActionButton.swift
  Eggong/Eggong/Presentation/Home/HomeAssistantView/HomePlaceCardView.swift
  Eggong/Eggong/Presentation/PlaceDetail/PlaceDetailView.swift
Labels: Reviewing, Feather
