Repository DeveloperAcademy-POSTECH/2024-MacC-M05-SinNaReeSieous, pull requests merged in 2025-01, with the labels that each got.

#114 [Fix] #113 - 공유 캡쳐 이미지 다이소 아이콘 수정 및 폰트 적용
  ZipZipSa/ZipZipSa/Presentation/ShareCaptureView/ShareCaptureCardHeaderView.swift
  ZipZipSa/ZipZipSa/Presentation/ShareCaptureView/ShareCaptureCardView.swift
Labels: Reviewing, Nagi

#116 [Feat] #115 - HomeData 삭제 기능 추가
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/Presentation/HomeList/HomeListView.swift
  ZipZipSa/ZipZipSa/Presentation/Main/MainView.swift
Labels: Reviewing, Nagi

#120 [Fix] #119 - OnboardingView 및 SettingView 카테고리 시간 변경
  ZipZipSa/ZipZipSa/Data/Model/OnboardingCategory.swift
  ZipZipSa/ZipZipSa/Presentation/Setting/CategoryChangeView.swift
Labels: Reviewing, Lemony

#122 [Chore] #121 - 집집사 겨울앱아이콘(크리스마스앱아이콘) 적용
  ZipZipSa/ZipZipSa.xcodeproj/project.pbxproj
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/AppIconWinter.appiconset/Contents.json
  ZipZipSa/ZipZipSa/Resource/Asset/Assets.xcassets/AppIconWinter.appiconset/appIconWinter.png
Labels: Reviewing, Feather
